<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugincsNavigationTable extends Doctrine_Table
{
	public function isPopulated()
	{
		return ($this->createQuery()->count() > 1);
	}
	public function getNavigationRoot()
	{
		return $this->createQuery()->where('level = ?', 0)->fetchOne();
	}
	
	public function setForm(&$form)
	{
		if($form->getObject()->getContent())
		{
			parent::setForm($form);
		}
		return $form;
	}
}