csNavigation:
  actAs:  
    NestedSet:
      hasManyRoots: true
  columns:
    name:     
      type:   string(255)
    route:    
      type:   string(255)
    protected:
      type:   boolean
      default: false
    locked:
      type:   boolean
      default: false

# csNavigationMenu:
#   columns:
#     title:  string(255)
#     description: string(255)
#     root:   integer
#   relations:
#     csNavigationItem:
#       local:    root
#       foreign:  id