csNavigation:
  actAs:  
    NestedSet:
      hasManyRoots: true
  columns:
    name:     
      type:   string(255)
    route:    
      type:   string(255)
    protected:
      type:   boolean
      default: false
    locked:
      type:   boolean
      default: false
    